### ISSUE TITLE
Issues with chef client version 12.4.1

### ISSUE THREAD

**Issue by ianmiell** [IshentRas/cookbook-openshift3#157]
We use a medieval version of Chef (12.4.1).

This trips up on a couple of things - a yum dep is required in metadata.rb (which I've added here - hope that's ok):

https://github.com/IshentRas/cookbook-openshift3/commit/557039e69f834c5e806ba31ccc2ef70cea771414

The error thrown was:

```
================================================================================
Recipe Compile Error in /root/chef-solo-example/cookbooks/cookbook-openshift3/recipes/default.rb
================================================================================

NoMethodError
-------------
No resource or method named `yum_repository' for `Chef::Recipe "common"'

Cookbook Trace:
---------------
  /root/chef-solo-example/cookbooks/cookbook-openshift3/recipes/common.rb:52:in `block in from_file'
  /root/chef-solo-example/cookbooks/cookbook-openshift3/recipes/common.rb:51:in `each'
  /root/chef-solo-example/cookbooks/cookbook-openshift3/recipes/common.rb:51:in `from_file'
  /root/chef-solo-example/cookbooks/cookbook-openshift3/recipes/default.rb:36:in `from_file'

```

Also, there is an issue with having a 'notifies' ruby_block in a provider. 

```
Recipe: cookbook-openshift3::master_cluster
  * openshift_create_master[Create master configuration file] action create
    
    ================================================================================
    Error executing action `create` on resource 'openshift_create_master[Create master configuration file]'
    ================================================================================
    
    Chef::Exceptions::ResourceNotFound
    ----------------------------------
    resource template[/etc/origin/master/master-config.yaml] is configured to notify resource ruby_block[Restart API] with action run, but ruby_block[Restart API] cannot be found in the resour
ce collection. template[/etc/origin/master/master-config.yaml] is defined in /root/chef-solo-example/cookbooks/cookbook-openshift3/providers/openshift_create_master.rb:44:in `block in class_fr
om_file'
    
    Resource Declaration:
    ---------------------
    # In /root/chef-solo-example/cookbooks/cookbook-openshift3/recipes/master_cluster.rb
    
    266: openshift_create_master 'Create master configuration file' do
    267:   named_certificate node['cookbook-openshift3']['openshift_master_named_certificates']
    268:   origins node['cookbook-openshift3']['erb_corsAllowedOrigins'].uniq
    269:   master_file node['cookbook-openshift3']['openshift_master_config_file']
    270:   etcd_servers etcd_servers
    271:   masters_size master_servers.size
    272:   openshift_service_type node['cookbook-openshift3']['openshift_service_type']
    273:   standalone_registry node['cookbook-openshift3']['deploy_standalone_registry']
    274:   cluster true
    275: end
    276: 
    
    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo-example/cookbooks/cookbook-openshift3/recipes/master_cluster.rb:266:in `from_file'
    
    openshift_create_master("Create master configuration file") do
      action [:create]
      updated true
      updated_by_last_action true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :openshift_create_master
      cookbook_name :"cookbook-openshift3"
      recipe_name "master_cluster"
      origins ["127.0.0.1", "localhost", "master1.vagrant.test", "openshift", "openshift.default", "openshift.default.svc", "openshift.default.svc.cluster.local", "kubernetes", "kubernetes.def
ault", "kubernetes.default.svc", "kubernetes.default.svc.cluster.local", "172.30.0.1"]
      master_file "/etc/origin/master/master-config.yaml"
      etcd_servers [{"fqdn"=>"etcd1.vagrant.test", "ipaddress"=>"172.28.128.5"}, {"fqdn"=>"etcd2.vagrant.test", "ipaddress"=>"172.28.128.4"}, {"fqdn"=>"etcd3.vagrant.test", "ipaddress"=>"172.2
8.128.7"}]
      masters_size 2
      openshift_service_type "origin"
      cluster true
```

I'm testing a potential solution to this now.

**Comment by ianmiell** [comment]
Does this work 'everywhere'?

```
diff --git a/providers/openshift_create_master.rb b/providers/openshift_create_master.rb
index e5d8105..2e7c311 100644
--- a/providers/openshift_create_master.rb
+++ b/providers/openshift_create_master.rb
@@ -51,7 +51,7 @@ action :create do
         masters_size: new_resource.masters_size,
         ose_major_version: node['cookbook-openshift3']['deploy_containerized'] == true ? node['cookbook-openshift3']['openshift_docker_image_version'] : node['cookbook-openshift3']['ose_major
       )
+      unless node['chef_packages']['chef']['version'] == '12.4.1'
         notifies :run, 'ruby_block[Restart API]', :immediately
+       end
     end
@@ -66,7 +66,9 @@ action :create do
         masters_size: new_resource.masters_size,
         ose_major_version: node['cookbook-openshift3']['deploy_containerized'] == true ? node['cookbook-openshift3']['openshift_docker_image_version'] : node['cookbook-openshift3']['ose_major
       )
-      notifies :run, 'ruby_block[Restart Master]', :immediately
+      unless node['chef_packages']['chef']['version'] == '12.4.1'
+        notifies :run, 'ruby_block[Restart Master]', :immediately
+      end
     end
   end
   new_resource.updated_by_last_action(true)
```

**Comment by ianmiell** [comment]
https://gist.github.com/jtimberman/428751

**Comment by IshentRas** [comment]
Closing
