### ISSUE TITLE
3.9 chef error

### ISSUE THREAD

**Issue by ianmiell** [IshentRas/cookbook-openshift3#274]
Got this error:

```
Generated at 2018-09-25 17:00:40 +0000
TypeError: no implicit conversion of String into Integer
/var/chef/cache/cookbooks/cookbook-openshift3/libraries/openshift_helper.rb:92:in `[]'
/var/chef/cache/cookbooks/cookbook-openshift3/libraries/openshift_helper.rb:92:in `on_certificate_server?'
/var/chef/cache/cookbooks/cookbook-openshift3/libraries/openshift_helper.rb:96:in `on_control_plane_server?'
/var/chef/cache/cookbooks/cookbook-openshift3/libraries/openshift_helper.rb:100:in `should_be_configured?'
/var/chef/cache/cookbooks/cookbook-openshift3/recipes/default.rb:8:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/cookbook_version.rb:205:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/run_context.rb:343:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/run_context/cookbook_compiler.rb:163:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/run_context/cookbook_compiler.rb:160:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/run_context/cookbook_compiler.rb:160:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/run_context/cookbook_compiler.rb:77:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/run_context.rb:192:in `load'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/client.rb:513:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/application/client.rb:457:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/application/client.rb:457:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/application/client.rb:441:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:58:in `load'
/usr/bin/chef-client:58:in `<main>'
```

with this test:

```
imiell   32283 32041  0 15:39 pts/10   00:00:13 /usr/bin/python /usr/local/bin/shutit build -l debug -d bash --echo --interactive 0 -m shutit-library/vagrant:shutit-library/virtualbox -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster test_config_dir test_multi_node_basic_cert_server -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster ose_version 3.9.0-1.el7.git.0.ba7faec -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster ose_major_version 3.9 -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster cookbook_branch master -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster chef_yum_cookbook_version latest -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster chef_iptables_cookbook_version latest -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster chef_selinux_policy_cookbook_version latest -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster chef_compat_resource_cookbook_version latest -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster inject_compat_resource false -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster chef_deploy_method server -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster chef_deploy_containerized false -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster do_upgrade_14_15 false -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster do_upgrade_15_36 false -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster do_upgrade_36_37 false -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster do_upgrade_37_39 false -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster openshift_docker_image_version v3.9.0 -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster adhoc_uninstall false -s tk.shutit.shutit_openshift_cluster.shutit_openshift_cluster adhoc_reset false --nocolor --echo
```

investigating...

**Comment by ianmiell** [comment]
Hmm, is this due to the different chef version?

No...

```
Relevant File Content:
----------------------
/var/chef/cache/cookbooks/cookbook-openshift3/libraries/openshift_helper.rb:

 85:      end
 86:
 87:      def on_first_etcd?
 88:        first_etcd['fqdn'] == node['fqdn']
 89:      end
 90:
 91:      def on_certificate_server?
 92>>       certificate_server['fqdn'] == node['fqdn']
 93:      end
 94:
 95:      def on_control_plane_server?
 96:        on_certificate_server? || on_etcd_server? || on_master_server?
 97:      end
 98:
 99:      def should_be_configured?
100:        on_control_plane_server? || on_node_server?
101:      end

```

**Comment by ianmiell** [comment]
Suspect method returns wrong thing in some way. Need to step through.

**Comment by ianmiell** [comment]
certificate_server[0]['fqdn'] works

**Comment by ianmiell** [comment]
I think this fixes it:

```
imiell@dali:/space/git/cookbook-openshift3  ⑂ master +  $  git diff
diff --git a/libraries/openshift_helper.rb b/libraries/openshift_helper.rb
index 59e0169..f1d1b99 100644
--- a/libraries/openshift_helper.rb
+++ b/libraries/openshift_helper.rb
@@ -49,7 +49,7 @@ module OpenShiftHelper
         when 0
           first_master
         else
-          Chef::Search::Query.new.search(:node, "role:#{node['cookbook-openshift3']['openshift_cluster_duty_discovery_id']}_openshift_certificate_server_duty")[0]
+          Chef::Search::Query.new.search(:node, "role:#{node['cookbook-openshift3']['openshift_cluster_duty_discovery_id']}_openshift_certificate_server_duty")[0][0]
         end
       else
         node['cookbook-openshift3']['certificate_server'] == {} ? first_master : node['cookbook-openshift3']['certificate_server']
```
