### ISSUE TITLE
Dnsmasq broken with 3.10 ng recipes

### ISSUE THREAD

**Issue by jperville** [IshentRas/cookbook-openshift3#287]
I tried to provision OSE v3.10 using the ng recipes of this cookbook.

I ran into the following issue : dnsmasq service fails to start (after being configured in the ng_node recipe).
Here is the dnsmasq logs:
```sh
Dec 19 11:02:08 ose-centos-74 systemd[1]: Starting DNS caching server....
Dec 19 11:02:08 ose-centos-74 dnsmasq[18863]: dnsmasq: DBus error: Connection ":1.47" is not allowed to own the service "uk.org.thekelleys.dnsmasq" due to security policies in the configuration file
Dec 19 11:02:08 ose-centos-74 systemd[1]: dnsmasq.service: main process exited, code=exited, status=5/NOTINSTALLED
Dec 19 11:02:08 ose-centos-74 systemd[1]: Unit dnsmasq.service entered failed state.
Dec 19 11:02:08 ose-centos-74 systemd[1]: dnsmasq.service failed.
Dec 19 11:02:41 ose-centos-74 systemd[1]: Started DNS caching server..
``` 

The symptom was that "docker pull openshift/node:v3.10" failed in ng_node.rb recipe (the actual reason was that the docker client could not resolve the docker registry hosts because the dns server from /etc/resolv.conf -dnsmasq- is down).

My workaround was to `service dbus restart` then `service dnsmasq restart`.

@IshentRas can you have a look please?

Full chef trace below:
```sh
           
           ================================================================================
           Error executing action `pull_if_missing` on resource 'docker_image[openshift/node]'
           ================================================================================
           
           Docker::Error::NotFoundError
           ----------------------------
           No such image: openshift/node:v3.10
           
           Cookbook Trace:
           ---------------
           /tmp/vagrant-cache/chef/cookbooks/docker/libraries/docker_image.rb:150:in `block in pull_image'
           /tmp/vagrant-cache/chef/cookbooks/docker/libraries/docker_base.rb:29:in `with_retries'
           /tmp/vagrant-cache/chef/cookbooks/docker/libraries/docker_image.rb:147:in `pull_image'
           /tmp/vagrant-cache/chef/cookbooks/docker/libraries/docker_image.rb:51:in `block in <class:DockerImage>'
           /tmp/vagrant-cache/chef/cookbooks/docker/libraries/docker_image.rb:56:in `block in <class:DockerImage>'
           
           Resource Declaration:
           ---------------------
           # In /tmp/vagrant-cache/chef/cookbooks/cookbook-openshift3/recipes/ng_node.rb
           
           111: docker_image node['cookbook-openshift3']['openshift_docker_node_image'] do
           112:   tag docker_version
           113:   action :pull_if_missing
           114: end
           115: 
           116: cookbook_file '/usr/local/bin/openshift-node' do
           117:   source 'openshift_node/openshift-node'
           118:   owner 'root'
           119:   group 'root'
           120:   mode '0500'
           121: end
           122: 
           123: systemd_unit "#{node['cookbook-openshift3']['openshift_service_type']}-node.service" do
           124:   content(Unit: {
           125:             Description: 'OpenShift Node',
           126:             After: ['docker.service', 'chronyd.service', 'ntpd.service', 'dnsmasq.service'],
           127:             Wants: ['docker.service', 'dnsmasq.service'],
           128:             Documentation: 'https://github.com/openshift/origin'
           129:           },
           130:           Service: {
           131:             Type: 'notify',
           132:             EnvironmentFile: "/etc/sysconfig/#{node['cookbook-openshift3']['openshift_service_type']}-node",
           133:             ExecStart: '/usr/local/bin/openshift-node',
           134:             LimitNOFILE: '65536',
           135:             LimitCORE: 'infinity',
           136:             WorkingDirectory: '/var/lib/origin/',
           137:             SyslogIdentifier: "#{node['cookbook-openshift3']['openshift_service_type']}-node",
           138:             Restart: 'always',
           139:             RestartSec: '5s',
           140:             TimeoutStartSec: '300',
           141:             OOMScoreAdjust: '-999'
           142:           },
           143:           Install: {
           144:             WantedBy: 'multi-user.target'
           145:           })
           146:   action :create
           147:   triggers_reload true
           148: end
           149: 
           150: ruby_block 'Configure Node settings' do
           151:   block do
           152:     node_settings = Chef::Util::FileEdit.new("/etc/sysconfig/#{node['cookbook-openshift3']['openshift_service_type']}-node")
           153:     node_settings.search_file_replace_line(/^OPTIONS=/, "OPTIONS=#{node['cookbook-openshift3']['openshift_node_start_options']}")
           154:     node_settings.search_file_replace_line(/^DEBUG_LOGLEVEL=/, "DEBUG_LOGLEVEL=#{node['cookbook-openshift3']['openshift_node_debug_level']}")
           155:     node_settings.search_file_replace_line(/^IMAGE_VERSION=/, "IMAGE_VERSION=#{docker_version}")
           156:     node_settings.write_file
           157:     node_settings = Chef::Util::FileEdit.new("/etc/sysconfig/#{node['cookbook-openshift3']['openshift_service_type']}-node")
           158:     node_settings.insert_line_if_no_match(/^OPTIONS=/, "OPTIONS=#{node['cookbook-openshift3']['openshift_node_start_options']}")
           159:     node_settings.insert_line_if_no_match(/^DEBUG_LOGLEVEL=/, "DEBUG_LOGLEVEL=#{node['cookbook-openshift3']['openshift_node_debug_level']}")
           160:     node_settings.insert_line_if_no_match(/^IMAGE_VERSION=/, "IMAGE_VERSION=#{docker_version}")
           161:     node_settings.write_file
           162:   end
           163: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/vagrant-cache/chef/cookbooks/cookbook-openshift3/recipes/ng_node.rb:111:in `from_file'
           
           docker_image("openshift/node") do
             action [:pull_if_missing]
             default_guard_interpreter :default
             declared_type :docker_image
             cookbook_name "cookbook-openshift3"
             recipe_name "ng_node"
             tag "v3.10"
             connection #<Docker::Connection:0x00000000063e7708 @url="unix:///", @options={:socket=>"/var/run/docker.sock", :read_timeout=>120}>
           end
           
           System Info:
           ------------
           chef_version=14.8.12
           platform=centos
           platform_version=7.4.1708
           ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client
```

**Comment by IshentRas** [comment]
Ok I'll have a look. I'm away at the moment. Will check next week

**Comment by IshentRas** [comment]
@jperville I was not able to replicate the issue. I even created a new server from scratch and used the allinone script and everything went OK.

**Comment by jperville** [comment]
I'll send you full reproduction instructions in the next days (still in holiday). Cheers

**Comment by IshentRas** [comment]
No worries. Enjoy your holiday
